config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  devise_for :users
  resources :users, only: %i[show update]
  get 'users/:id/show_json', to: 'users#show_json', as: 'user_show_json'
  resources :users do
    member do
      post :toggle_follow
    end
  end

  resources :posts, only: %i[create update destroy show] do
    member do
      post :toggle_like
      get :likers
      resources :comments, only: %i[create index]
    end
  end
  get 'timeline', to: 'posts#index'
  get 'timeline/followings', to: 'posts#idx_followings'
  get 'timeline/user/:id', to: 'posts#idx_user', as: 'timeline_user'
  get 'timeline/likes', to: 'posts#idx_likes', as: 'timeline_likes'
  get 'posts/more', to: 'posts#more_posts', as: 'more_posts'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/user.rb
class User < ApplicationRecord
  # バリデーション（アルファベットのみ、スペース禁止、20文字以内）
  validates :username, presence: true, length: { maximum: 20 },
                       format: { with: /\A[a-zA-Z]*\z/, message: 'only allows letters' }
  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }

  # ポスト機能 ----------------------------------------------------------------
  # ユーザーは複数のPostを持ち、ユーザーが削除されたらpostも削除
  has_many :posts, dependent: :destroy

  # フォロー機能 ----------------------------------------------------------------
  # ユーザーは複数のフォローを持ち、ユーザーが削除されたらフォローも削除
  has_many :active_relationships, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  # ユーザーは複数のフォロワーを持ち、ユーザーが削除されたらフォロワーも削除
  has_many :passive_relationships, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy
  # ユーザーは複数のフォローを持ち、フォローしているユーザーを取得
  has_many :followings, through: :active_relationships, source: :followed
  has_many :following_posts, through: :followings, source: :posts
  # ユーザーは複数のフォロワーを持ち、フォローされているユーザーを取得
  has_many :followers, through: :passive_relationships, source: :follower

  # ユーザーをフォローする
  def follow(other_user)
    followings << other_user unless self == other_user
  end

  # ユーザーをフォロー解除する
  def unfollow(other_user)
    relationship = active_relationships.find_by(followed_id: other_user.id)
    relationship&.destroy
  end

  # ユーザーがフォローしているかどうか
  def following?(other_user)
    followings.include?(other_user)
  end

  # いいね機能 ------------------------------------------------------------------
  # ユーザーは複数のいいねを持ち、ユーザーが削除されたらいいねも削除
  has_many :likes, dependent: :destroy
  # ユーザーは複数のいいねを持ち、いいねした投稿を取得
  has_many :liked_posts, through: :likes, source: :post

  # deviceの設定 ---------------------------------------------------------------
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         authentication_keys: [:username] # 認証のキーをメールから名前へ

  validates_uniqueness_of :username
  validates_presence_of :username

  # usernameを利用してログイン
  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if (username = conditions.delete(:login))
      where(conditions).where(['username = :value', { value: username }]).first
    else
      where(conditions).first
    end
  end

  def email_required?
    false
  end

  def email_changed?
    true
  end

  def will_save_change_to_email?
    true
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: %i[edit update follow unfollow]

  def show
    @user = User.find(params[:id])
  end

  def show_json
    @target_user = User.find(params[:id])
    @current_user = current_user
    is_followed = @current_user&.following?(@target_user)
    render json: @target_user.as_json.merge(is_followed:)
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = 'プロフィールを更新しました'
      redirect_to user_path(@user)
    else
      flash[:alert] = 'プロフィールの更新に失敗しました'
      render 'show'
    end
  end

  def toggle_follow
    user = User.find(params[:id])
    if current_user.following?(user)
      current_user.unfollow(user)
      render json: { status: 'unfollowed' }
    else
      current_user.follow(user)
      render json: { status: 'followed' }
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :profile, :blog_url)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.haml
%h1.text-center.font-weight-bold.mb-4.border-bottom info

.card.mb-3.w-50
  - if current_user == @user
    .card-header.d-flex.justify-content-between
      %h5.card-title
        = @user.username
      = link_to 'アカウントを編集', edit_user_registration_path,
                class: 'btn btn-primary'
    = form_with(model: @user, local: true) do |form|
      .card-body
        %p.card-text.d-flex.flex-column.align-items-center
          %strong プロフィール:
          .form-group.text-center
            = form.text_area :profile, class: 'form-control', maxlength: 200
        %p.card-text.d-flex.flex-column.align-items-center
          %strong ブログURL:
          .form-group.text-center
            = form.text_area :blog_url, class: 'form-control'
        .d-flex.justify-content-end.mb-3
          = form.submit '更新', class: 'btn btn-primary'

  - else
    .card-header.d-flex.justify-content-between
      %h5.card-title
        = @user.username
    .card-body
      %p.card-text.d-flex.flex-column.align-items-center
        %strong プロフィール:
        = @user.profile
      %p.card-text.d-flex.flex-column.align-items-center
        %strong ブログURL:
        = link_to @user.blog_url, @user.blog_url

%hr.w-25
.d-flex.justify-content-between.mt-4.w-25{ style: 'min-width: 185px;' }
  - if user_signed_in?
    = link_to 'ログアウト', destroy_user_session_path,
              data: { turbo_method: :delete },
              class: 'btn btn-outline-secondary'
  = link_to 'timeline', timeline_path, class: 'btn btn-secondary'